import type { Category, PieceType } from "./types";

/* Fit vocabularies. Fit describes silhouette on the body. */
export const TOP_FITS = ["fitted", "regular", "relaxed", "oversized", "boxy"] as const;
export const OUTER_FITS = ["fitted", "regular", "relaxed", "oversized"] as const;
export const PANT_FITS = ["skinny", "slim", "straight", "relaxed", "baggy", "wide"] as const;
export const SHORT_FITS = ["slim", "regular", "relaxed", "baggy"] as const;
export const SKIRT_FITS = ["mini", "midi", "maxi"] as const;
export const DRESS_FITS = ["fitted", "a-line", "relaxed", "slip", "wrap"] as const;
export const JUMPSUIT_FITS = ["fitted", "relaxed", "wide"] as const;

export const FIT_LABELS: Record<string, string> = {
  fitted: "Fitted",
  regular: "Regular",
  relaxed: "Relaxed",
  oversized: "Oversized",
  boxy: "Boxy",
  skinny: "Skinny",
  slim: "Slim",
  straight: "Straight",
  baggy: "Baggy",
  wide: "Wide",
  mini: "Mini",
  midi: "Midi",
  maxi: "Maxi",
  "a-line": "A-line",
  slip: "Slip",
  wrap: "Wrap",
};

/** Fits that read as loose. Used for a small formality adjustment. */
export const LOOSE_FITS = new Set(["oversized", "boxy", "baggy", "wide"]);

export const VARIANT_LABELS: Record<string, string> = {
  "low-top": "Low-top",
  "high-top": "High-top",
  chunky: "Chunky",
  running: "Running",
  retro: "Retro",
  "slip-on": "Slip-on",
  chelsea: "Chelsea",
  "lace-up": "Lace-up",
  work: "Work",
  hiking: "Hiking",
  western: "Western",
  penny: "Penny",
  tassel: "Tassel",
  horsebit: "Horsebit",
  oxford: "Oxford",
  derby: "Derby",
  monk: "Monk strap",
  slide: "Slide",
  strap: "Strap",
  "flip-flop": "Flip-flop",
  cork: "Cork footbed",
  baseball: "Baseball",
  dad: "Dad cap",
  "five-panel": "Five-panel",
  trucker: "Trucker",
  cuffed: "Cuffed",
  fisherman: "Fisherman",
  slouchy: "Slouchy",
  leather: "Leather",
  canvas: "Canvas",
  web: "Webbing",
  "knit-scarf": "Knit",
  "wool-scarf": "Wool",
  "silk-scarf": "Silk",
  wayfarer: "Wayfarer",
  aviator: "Aviator",
  round: "Round",
  sport: "Sport",
  "leather-strap": "Leather strap",
  "metal-bracelet": "Metal bracelet",
  minimal: "Minimal",
  digital: "Digital",
  backpack: "Backpack",
  crossbody: "Crossbody",
  messenger: "Messenger",
  duffel: "Duffel",
  "canvas-tote": "Canvas",
  "leather-tote": "Leather",
};

/* Reusable option lists */
const CASUAL_TOP_PATTERNS = ["solid", "stripe", "graphic", "logo", "print", "colorblock"] as const;
const SHIRT_PATTERNS = ["solid", "stripe", "check", "print", "textured"] as const;
const KNIT_PATTERNS = ["solid", "stripe", "textured", "colorblock", "logo"] as const;
const PLAIN = ["solid", "textured"] as const;
const BOTTOM_PATTERNS = ["solid", "check", "textured"] as const;

export const CATALOG: readonly PieceType[] = [
  /* ---------- Tops ---------- */
  {
    id: "t-shirt",
    category: "top",
    label: "T-shirt",
    plural: "T-shirts",
    icon: "tee",
    fitOptions: TOP_FITS,
    materialOptions: ["cotton", "jersey", "linen"],
    defaultWeight: "light",
    baseWarmth: 1,
    baseFormality: 2,
    suggestedColors: ["white", "black", "off-white", "grey", "navy", "beige"],
    patternOptions: CASUAL_TOP_PATTERNS,
  },
  {
    id: "long-sleeve-tee",
    category: "top",
    label: "Long-sleeve tee",
    plural: "Long-sleeve tees",
    icon: "longsleeve",
    fitOptions: TOP_FITS,
    materialOptions: ["cotton", "jersey"],
    defaultWeight: "light",
    baseWarmth: 2,
    baseFormality: 2,
    suggestedColors: ["white", "black", "grey", "navy", "cream", "olive"],
    patternOptions: CASUAL_TOP_PATTERNS,
  },
  {
    id: "tank-top",
    category: "top",
    label: "Tank top",
    plural: "Tank tops",
    icon: "tank",
    fitOptions: TOP_FITS,
    materialOptions: ["cotton", "jersey"],
    defaultWeight: "light",
    baseWarmth: 1,
    baseFormality: 1,
    suggestedColors: ["white", "black", "grey", "off-white"],
    patternOptions: ["solid", "stripe", "graphic"],
  },
  {
    id: "polo",
    category: "top",
    label: "Polo",
    plural: "Polos",
    icon: "polo",
    fitOptions: TOP_FITS,
    materialOptions: ["cotton", "knit", "jersey"],
    defaultWeight: "light",
    baseWarmth: 1,
    baseFormality: 3,
    suggestedColors: ["navy", "white", "black", "forest", "cream", "burgundy"],
    patternOptions: ["solid", "stripe", "textured"],
  },
  {
    id: "henley",
    category: "top",
    label: "Henley",
    plural: "Henleys",
    icon: "henley",
    fitOptions: TOP_FITS,
    materialOptions: ["cotton", "jersey", "knit"],
    defaultWeight: "light",
    baseWarmth: 2,
    baseFormality: 2,
    suggestedColors: ["white", "cream", "grey", "navy", "olive"],
    patternOptions: ["solid", "stripe", "textured"],
  },
  {
    id: "shirt",
    category: "top",
    label: "Shirt",
    plural: "Shirts",
    icon: "shirt",
    fitOptions: TOP_FITS,
    materialOptions: ["cotton", "linen", "twill", "denim", "corduroy", "silk"],
    defaultWeight: "light",
    baseWarmth: 2,
    baseFormality: 3,
    suggestedColors: ["white", "light-blue", "off-white", "navy", "sage", "black"],
    patternOptions: SHIRT_PATTERNS,
  },
  {
    id: "dress-shirt",
    category: "top",
    label: "Dress shirt",
    plural: "Dress shirts",
    icon: "shirt",
    fitOptions: ["fitted", "regular", "relaxed"],
    materialOptions: ["cotton", "twill", "linen"],
    defaultWeight: "light",
    baseWarmth: 2,
    baseFormality: 4,
    suggestedColors: ["white", "light-blue", "off-white", "sky", "black"],
    patternOptions: ["solid", "stripe", "check"],
  },

  /* ---------- Layers ---------- */
  {
    id: "crewneck-sweater",
    category: "layer",
    label: "Crewneck sweater",
    plural: "Crewneck sweaters",
    icon: "sweater",
    fitOptions: TOP_FITS,
    materialOptions: ["knit", "wool", "cotton", "cashmere"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 3,
    suggestedColors: ["navy", "grey", "cream", "black", "camel", "forest"],
    patternOptions: KNIT_PATTERNS,
  },
  {
    id: "hoodie",
    category: "layer",
    label: "Hoodie",
    plural: "Hoodies",
    icon: "hoodie",
    fitOptions: TOP_FITS,
    materialOptions: ["cotton", "fleece", "jersey"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 1,
    suggestedColors: ["grey", "black", "navy", "off-white", "olive", "brown"],
    patternOptions: ["solid", "graphic", "logo", "colorblock"],
  },
  {
    id: "sweatshirt",
    category: "layer",
    label: "Sweatshirt",
    plural: "Sweatshirts",
    icon: "sweater",
    fitOptions: TOP_FITS,
    materialOptions: ["cotton", "fleece", "jersey"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 2,
    suggestedColors: ["grey", "navy", "off-white", "black", "sage", "burgundy"],
    patternOptions: ["solid", "graphic", "logo", "colorblock"],
  },
  {
    id: "cardigan",
    category: "layer",
    label: "Cardigan",
    plural: "Cardigans",
    icon: "cardigan",
    fitOptions: TOP_FITS,
    materialOptions: ["knit", "wool", "cotton", "cashmere"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 3,
    suggestedColors: ["cream", "grey", "navy", "camel", "black", "forest"],
    patternOptions: KNIT_PATTERNS,
  },
  {
    id: "turtleneck",
    category: "layer",
    label: "Turtleneck",
    plural: "Turtlenecks",
    icon: "turtleneck",
    fitOptions: ["fitted", "regular", "relaxed"],
    materialOptions: ["knit", "wool", "cotton", "cashmere"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 3.5,
    suggestedColors: ["black", "cream", "grey", "navy", "camel", "burgundy"],
    patternOptions: PLAIN,
  },
  {
    id: "quarter-zip",
    category: "layer",
    label: "Quarter-zip",
    plural: "Quarter-zips",
    icon: "quarterzip",
    fitOptions: TOP_FITS,
    materialOptions: ["knit", "cotton", "fleece", "wool"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 3,
    suggestedColors: ["navy", "grey", "black", "forest", "cream"],
    patternOptions: PLAIN,
  },
  {
    id: "overshirt",
    category: "layer",
    label: "Overshirt",
    plural: "Overshirts",
    icon: "overshirt",
    fitOptions: ["regular", "relaxed", "oversized", "boxy"],
    materialOptions: ["cotton", "twill", "corduroy", "wool", "denim", "canvas"],
    defaultWeight: "mid",
    baseWarmth: 2.5,
    baseFormality: 3,
    suggestedColors: ["olive", "navy", "beige", "black", "brown", "denim"],
    patternOptions: ["solid", "check", "textured"],
  },
  {
    id: "fleece",
    category: "layer",
    label: "Fleece",
    plural: "Fleeces",
    icon: "quarterzip",
    fitOptions: ["regular", "relaxed", "oversized"],
    materialOptions: ["fleece", "polyester"],
    defaultWeight: "mid",
    baseWarmth: 3.5,
    baseFormality: 1.5,
    suggestedColors: ["cream", "navy", "black", "forest", "brown", "grey"],
    patternOptions: ["solid", "colorblock"],
  },
  {
    id: "vest",
    category: "layer",
    label: "Vest",
    plural: "Vests",
    icon: "vest",
    fitOptions: ["fitted", "regular", "relaxed"],
    materialOptions: ["nylon", "wool", "fleece", "cotton"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 2,
    suggestedColors: ["black", "navy", "olive", "beige", "grey"],
    patternOptions: PLAIN,
  },

  /* ---------- Outerwear ---------- */
  {
    id: "denim-jacket",
    category: "outerwear",
    label: "Denim jacket",
    plural: "Denim jackets",
    icon: "jacket",
    fitOptions: OUTER_FITS,
    materialOptions: ["denim"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 2,
    suggestedColors: ["denim", "light-blue", "black", "indigo", "off-white"],
    patternOptions: PLAIN,
  },
  {
    id: "bomber",
    category: "outerwear",
    label: "Bomber jacket",
    plural: "Bomber jackets",
    icon: "jacket",
    fitOptions: OUTER_FITS,
    materialOptions: ["nylon", "leather", "suede", "cotton", "wool"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 2.5,
    suggestedColors: ["black", "olive", "navy", "brown", "beige"],
    patternOptions: PLAIN,
  },
  {
    id: "leather-jacket",
    category: "outerwear",
    label: "Leather jacket",
    plural: "Leather jackets",
    icon: "jacket",
    fitOptions: OUTER_FITS,
    materialOptions: ["leather", "suede"],
    defaultWeight: "mid",
    baseWarmth: 3.5,
    baseFormality: 3,
    suggestedColors: ["black", "brown", "chocolate", "tan", "burgundy"],
    patternOptions: PLAIN,
  },
  {
    id: "blazer",
    category: "outerwear",
    label: "Blazer",
    plural: "Blazers",
    icon: "blazer",
    fitOptions: OUTER_FITS,
    materialOptions: ["wool", "cotton", "linen", "twill", "corduroy"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 4.5,
    suggestedColors: ["navy", "charcoal", "black", "beige", "grey", "forest"],
    patternOptions: ["solid", "check", "textured", "stripe"],
  },
  {
    id: "harrington",
    category: "outerwear",
    label: "Harrington jacket",
    plural: "Harrington jackets",
    icon: "jacket",
    fitOptions: OUTER_FITS,
    materialOptions: ["cotton", "nylon", "twill"],
    defaultWeight: "light",
    baseWarmth: 2.5,
    baseFormality: 3,
    suggestedColors: ["navy", "beige", "black", "olive", "burgundy"],
    patternOptions: PLAIN,
  },
  {
    id: "chore-jacket",
    category: "outerwear",
    label: "Chore jacket",
    plural: "Chore jackets",
    icon: "overshirt",
    fitOptions: ["regular", "relaxed", "oversized"],
    materialOptions: ["cotton", "canvas", "twill", "corduroy", "denim"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 2.5,
    suggestedColors: ["navy", "olive", "beige", "brown", "black", "denim"],
    patternOptions: PLAIN,
  },
  {
    id: "trench-coat",
    category: "outerwear",
    label: "Trench coat",
    plural: "Trench coats",
    icon: "trench",
    fitOptions: OUTER_FITS,
    materialOptions: ["cotton", "twill", "polyester"],
    defaultWeight: "mid",
    baseWarmth: 3,
    baseFormality: 4,
    suggestedColors: ["beige", "sand", "black", "navy", "olive"],
    patternOptions: PLAIN,
  },
  {
    id: "wool-coat",
    category: "outerwear",
    label: "Wool coat",
    plural: "Wool coats",
    icon: "coat",
    fitOptions: OUTER_FITS,
    materialOptions: ["wool", "cashmere"],
    defaultWeight: "heavy",
    baseWarmth: 4.5,
    baseFormality: 4.5,
    suggestedColors: ["charcoal", "camel", "black", "navy", "grey", "beige"],
    patternOptions: ["solid", "check", "textured"],
  },
  {
    id: "puffer",
    category: "outerwear",
    label: "Puffer jacket",
    plural: "Puffer jackets",
    icon: "puffer",
    fitOptions: OUTER_FITS,
    materialOptions: ["nylon", "polyester", "tech"],
    defaultWeight: "heavy",
    baseWarmth: 5,
    baseFormality: 1.5,
    suggestedColors: ["black", "navy", "olive", "beige", "off-white", "brown"],
    patternOptions: ["solid", "colorblock"],
  },
  {
    id: "parka",
    category: "outerwear",
    label: "Parka",
    plural: "Parkas",
    icon: "parka",
    fitOptions: ["regular", "relaxed", "oversized"],
    materialOptions: ["nylon", "cotton", "tech", "polyester"],
    defaultWeight: "heavy",
    baseWarmth: 5,
    baseFormality: 2,
    suggestedColors: ["olive", "navy", "black", "beige", "brown"],
    patternOptions: PLAIN,
  },
  {
    id: "rain-jacket",
    category: "outerwear",
    label: "Rain jacket",
    plural: "Rain jackets",
    icon: "parka",
    fitOptions: ["regular", "relaxed", "oversized"],
    materialOptions: ["nylon", "tech", "polyester"],
    defaultWeight: "light",
    baseWarmth: 2.5,
    baseFormality: 1.5,
    suggestedColors: ["black", "navy", "olive", "yellow", "beige"],
    patternOptions: ["solid", "colorblock"],
  },

  /* ---------- Bottoms ---------- */
  {
    id: "jeans",
    category: "bottom",
    label: "Jeans",
    plural: "Jeans",
    icon: "jeans",
    fitOptions: PANT_FITS,
    materialOptions: ["denim"],
    defaultWeight: "mid",
    baseWarmth: 2.5,
    baseFormality: 2.5,
    suggestedColors: ["denim", "light-blue", "indigo", "black", "off-white", "grey"],
    patternOptions: PLAIN,
  },
  {
    id: "chinos",
    category: "bottom",
    label: "Chinos",
    plural: "Chinos",
    icon: "trousers",
    fitOptions: PANT_FITS,
    materialOptions: ["cotton", "twill"],
    defaultWeight: "mid",
    baseWarmth: 2.5,
    baseFormality: 3.5,
    suggestedColors: ["beige", "navy", "olive", "sand", "black", "grey"],
    patternOptions: ["solid"],
  },
  {
    id: "trousers",
    category: "bottom",
    label: "Trousers",
    plural: "Trousers",
    icon: "trousers",
    fitOptions: PANT_FITS,
    materialOptions: ["wool", "cotton", "twill", "linen", "polyester"],
    defaultWeight: "mid",
    baseWarmth: 2.5,
    baseFormality: 4,
    suggestedColors: ["black", "charcoal", "navy", "grey", "beige", "brown"],
    patternOptions: BOTTOM_PATTERNS,
  },
  {
    id: "cargo-pants",
    category: "bottom",
    label: "Cargo pants",
    plural: "Cargo pants",
    icon: "trousers",
    fitOptions: ["slim", "straight", "relaxed", "baggy", "wide"],
    materialOptions: ["cotton", "twill", "nylon", "tech"],
    defaultWeight: "mid",
    baseWarmth: 2.5,
    baseFormality: 2,
    suggestedColors: ["olive", "black", "beige", "sand", "grey", "brown"],
    patternOptions: ["solid"],
  },
  {
    id: "sweatpants",
    category: "bottom",
    label: "Sweatpants",
    plural: "Sweatpants",
    icon: "sweatpants",
    fitOptions: ["slim", "straight", "relaxed", "baggy", "wide"],
    materialOptions: ["cotton", "fleece", "jersey", "tech"],
    defaultWeight: "mid",
    baseWarmth: 2.5,
    baseFormality: 1,
    suggestedColors: ["grey", "black", "navy", "off-white", "olive"],
    patternOptions: ["solid", "logo"],
  },
  {
    id: "shorts",
    category: "bottom",
    label: "Shorts",
    plural: "Shorts",
    icon: "shorts",
    fitOptions: SHORT_FITS,
    materialOptions: ["cotton", "linen", "twill", "nylon", "tech"],
    defaultWeight: "light",
    baseWarmth: 1,
    baseFormality: 2,
    suggestedColors: ["beige", "navy", "black", "olive", "sand", "white"],
    patternOptions: ["solid", "stripe", "check", "print"],
  },
  {
    id: "denim-shorts",
    category: "bottom",
    label: "Denim shorts",
    plural: "Denim shorts",
    icon: "shorts",
    fitOptions: SHORT_FITS,
    materialOptions: ["denim"],
    defaultWeight: "light",
    baseWarmth: 1,
    baseFormality: 2,
    suggestedColors: ["denim", "light-blue", "black", "indigo"],
    patternOptions: ["solid"],
  },
  {
    id: "skirt",
    category: "bottom",
    label: "Skirt",
    plural: "Skirts",
    icon: "skirt",
    fitOptions: SKIRT_FITS,
    materialOptions: ["cotton", "denim", "wool", "linen", "silk", "leather", "polyester"],
    defaultWeight: "light",
    baseWarmth: 1.5,
    baseFormality: 3,
    suggestedColors: ["black", "denim", "beige", "navy", "cream", "olive"],
    patternOptions: ["solid", "check", "print", "stripe"],
  },

  /* ---------- Footwear ---------- */
  {
    id: "sneakers",
    category: "footwear",
    label: "Sneakers",
    plural: "Sneakers",
    icon: "sneaker",
    variantOptions: ["low-top", "high-top", "chunky", "running", "retro", "slip-on"],
    materialOptions: ["leather", "canvas", "suede", "mesh", "tech"],
    defaultWeight: "mid",
    baseWarmth: 2,
    baseFormality: 2,
    suggestedColors: ["white", "black", "off-white", "grey", "navy", "beige"],
    patternOptions: ["solid", "colorblock"],
  },
  {
    id: "boots",
    category: "footwear",
    label: "Boots",
    plural: "Boots",
    icon: "boot",
    variantOptions: ["chelsea", "lace-up", "work", "hiking", "western"],
    materialOptions: ["leather", "suede", "rubber", "canvas"],
    defaultWeight: "heavy",
    baseWarmth: 3.5,
    baseFormality: 3,
    suggestedColors: ["black", "brown", "chocolate", "tan", "sand"],
    patternOptions: ["solid"],
  },
  {
    id: "loafers",
    category: "footwear",
    label: "Loafers",
    plural: "Loafers",
    icon: "loafer",
    variantOptions: ["penny", "tassel", "horsebit"],
    materialOptions: ["leather", "suede"],
    defaultWeight: "mid",
    baseWarmth: 2,
    baseFormality: 4,
    suggestedColors: ["black", "brown", "chocolate", "tan", "burgundy"],
    patternOptions: ["solid"],
  },
  {
    id: "dress-shoes",
    category: "footwear",
    label: "Dress shoes",
    plural: "Dress shoes",
    icon: "dressshoe",
    variantOptions: ["oxford", "derby", "monk"],
    materialOptions: ["leather", "suede"],
    defaultWeight: "mid",
    baseWarmth: 2,
    baseFormality: 5,
    suggestedColors: ["black", "brown", "chocolate", "burgundy"],
    patternOptions: ["solid"],
  },
  {
    id: "sandals",
    category: "footwear",
    label: "Sandals",
    plural: "Sandals",
    icon: "sandal",
    variantOptions: ["slide", "strap", "flip-flop", "cork"],
    materialOptions: ["leather", "rubber", "suede", "canvas"],
    defaultWeight: "light",
    baseWarmth: 1,
    baseFormality: 1,
    suggestedColors: ["black", "brown", "tan", "white", "beige"],
    patternOptions: ["solid"],
  },

  /* ---------- Accessories ---------- */
  {
    id: "cap",
    category: "accessory",
    label: "Cap",
    plural: "Caps",
    icon: "cap",
    variantOptions: ["baseball", "dad", "five-panel", "trucker"],
    materialOptions: ["cotton", "twill", "nylon", "wool", "corduroy"],
    defaultWeight: "light",
    baseWarmth: 1,
    baseFormality: 1.5,
    suggestedColors: ["black", "navy", "beige", "olive", "white", "grey"],
    patternOptions: ["solid", "logo", "graphic"],
  },
  {
    id: "beanie",
    category: "accessory",
    label: "Beanie",
    plural: "Beanies",
    icon: "beanie",
    variantOptions: ["cuffed", "fisherman", "slouchy"],
    materialOptions: ["knit", "wool", "cotton", "cashmere"],
    defaultWeight: "mid",
    baseWarmth: 4,
    baseFormality: 1.5,
    suggestedColors: ["black", "grey", "navy", "cream", "olive", "burgundy"],
    patternOptions: ["solid", "stripe", "logo"],
  },
  {
    id: "belt",
    category: "accessory",
    label: "Belt",
    plural: "Belts",
    icon: "belt",
    variantOptions: ["leather", "canvas", "web"],
    materialOptions: ["leather", "suede", "canvas", "nylon"],
    defaultWeight: "light",
    baseWarmth: 0,
    baseFormality: 3,
    suggestedColors: ["black", "brown", "tan", "chocolate", "navy"],
    patternOptions: ["solid"],
  },
  {
    id: "scarf",
    category: "accessory",
    label: "Scarf",
    plural: "Scarves",
    icon: "scarf",
    variantOptions: ["knit-scarf", "wool-scarf", "silk-scarf"],
    materialOptions: ["wool", "knit", "cashmere", "silk", "cotton"],
    defaultWeight: "mid",
    baseWarmth: 4,
    baseFormality: 3,
    suggestedColors: ["grey", "black", "camel", "navy", "cream", "burgundy"],
    patternOptions: ["solid", "check", "stripe", "print"],
  },
  {
    id: "sunglasses",
    category: "accessory",
    label: "Sunglasses",
    plural: "Sunglasses",
    icon: "sunglasses",
    variantOptions: ["wayfarer", "aviator", "round", "sport"],
    materialOptions: ["polyester", "metal"],
    defaultWeight: "light",
    baseWarmth: 0,
    baseFormality: 2.5,
    suggestedColors: ["black", "brown", "tan", "grey"],
    patternOptions: ["solid"],
  },
  {
    id: "watch",
    category: "accessory",
    label: "Watch",
    plural: "Watches",
    icon: "watch",
    variantOptions: ["leather-strap", "metal-bracelet", "minimal", "digital", "sport"],
    materialOptions: ["metal", "leather", "rubber", "nylon"],
    defaultWeight: "light",
    baseWarmth: 0,
    baseFormality: 3,
    suggestedColors: ["black", "grey", "brown", "tan", "navy"],
    patternOptions: ["solid"],
  },
  {
    id: "bag",
    category: "accessory",
    label: "Bag",
    plural: "Bags",
    icon: "bag",
    variantOptions: ["backpack", "crossbody", "messenger", "duffel"],
    materialOptions: ["nylon", "leather", "canvas", "polyester", "suede"],
    defaultWeight: "light",
    baseWarmth: 0,
    baseFormality: 2.5,
    suggestedColors: ["black", "navy", "olive", "brown", "beige", "grey"],
    patternOptions: ["solid", "logo"],
  },
  {
    id: "tote",
    category: "accessory",
    label: "Tote",
    plural: "Totes",
    icon: "tote",
    variantOptions: ["canvas-tote", "leather-tote"],
    materialOptions: ["canvas", "leather", "nylon"],
    defaultWeight: "light",
    baseWarmth: 0,
    baseFormality: 2.5,
    suggestedColors: ["off-white", "black", "navy", "beige", "brown"],
    patternOptions: ["solid", "logo", "graphic"],
  },

  /* ---------- Full body ---------- */
  {
    id: "dress",
    category: "fullbody",
    label: "Dress",
    plural: "Dresses",
    icon: "dress",
    fitOptions: DRESS_FITS,
    materialOptions: ["cotton", "linen", "silk", "knit", "polyester", "denim", "wool"],
    defaultWeight: "light",
    baseWarmth: 1.5,
    baseFormality: 3.5,
    suggestedColors: ["black", "cream", "navy", "sage", "burgundy", "white"],
    patternOptions: ["solid", "print", "stripe", "check", "textured"],
  },
  {
    id: "jumpsuit",
    category: "fullbody",
    label: "Jumpsuit",
    plural: "Jumpsuits",
    icon: "jumpsuit",
    fitOptions: JUMPSUIT_FITS,
    materialOptions: ["cotton", "linen", "denim", "twill", "polyester"],
    defaultWeight: "mid",
    baseWarmth: 2,
    baseFormality: 3,
    suggestedColors: ["black", "navy", "olive", "beige", "denim"],
    patternOptions: ["solid", "print"],
  },
];

const byId = new Map(CATALOG.map((t) => [t.id, t]));

export function getPieceType(id: string): PieceType | undefined {
  return byId.get(id);
}

export function requirePieceType(id: string): PieceType {
  const t = byId.get(id);
  if (!t) throw new Error(`Unknown piece type: ${id}`);
  return t;
}

export function pieceTypesFor(category: Category): PieceType[] {
  return CATALOG.filter((t) => t.category === category);
}

/** True when the type is described by a fit (garment) rather than a variant. */
export function isGarment(type: PieceType): boolean {
  return type.fitOptions !== undefined;
}

export function fitLabel(fit: string): string {
  return FIT_LABELS[fit] ?? fit;
}

export function variantLabel(variant: string): string {
  return VARIANT_LABELS[variant] ?? variant;
}
